import Head from 'next/head'
import { Inter } from '@next/font/google'
import Homes from './home'
// import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <!-- Favicon --> */}

      </Head>
      <Homes />
    </>
  )
}

// const token;
// if (typeof window !== 'undefined') {
//   token = localStorage.getItem("authToken")
// }

// export async function getServerSideProps() {
//   const instance = axios.create({
//     baseURL: process.env.API_URL,
//     header: {
//       Authorization: token
//     }
//   });
// }